import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatNumber: (num: number | string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard',
    'clients': 'Clients',
    'estimates': 'Estimates',
    'items': 'Items',
    'reminders': 'Reminders',
    'insights': 'Business Insights',
    'sketch': 'Sketch Pad',
    'converter': 'Unit Conversion',
    'calculator': 'Calculator',
    'construction-calc': 'Engineering Toolset',
    'admin': 'Company Identity',
    'profile': 'My Profile',
    'logout': 'Logout',
    'super-admin': 'Super Admin',
    'menu': 'Menu',
    'total_estimates': 'Total Estimates',
    'active_clients': 'Active Clients',
    'pending_tasks': 'Pending Tasks',
    'total_revenue': 'Total Revenue',
    'recent_estimates': 'Recent Estimates',
    'view_all': 'View All',
    'create_new': 'Create New',
    'search': 'Search...',
    'settings': 'Settings',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'status': 'Status',
    'date': 'Date',
    'amount': 'Amount',
    'action': 'Action',
    'language': 'Language',
    'english': 'English',
    'hindi': 'Hindi',
    'gujarati': 'Gujarati',
    'category': 'Category',
    'from': 'From',
    'to': 'To',
    'enter_value': 'Enter Value',
    'converted_result': 'Converted Result',
    'copy': 'Copy Result',
    'copied': 'Copied!',
    'common_conversions': 'Common Conversions',
    'land_units': 'Land Units (India)',
    'did_you_know': 'Did you know?',
    'brass_info': 'In Indian construction, "Brass" is a common unit for volume, equal to 100 cubic feet. Our converter includes specialized units like Sut and Bigha for local project accuracy.',
    'converter_desc': 'Convert between various construction and engineering units.',
    'Length': 'Length',
    'Area': 'Area',
    'Volume': 'Volume',
    'Land (India)': 'Land (India)',
    'brick_work': 'Brick Work',
    'plastering': 'Plastering',
    'wall_paint': 'Wall Paint',
    'gypsum': 'Gypsum',
    'electrical': 'Electrical',
    'flooring': 'Flooring',
    'stone_work': 'Stone Work',
    'doors': 'Doors',
    'windows': 'Windows',
    'frame_work': 'Frame Work',
    'kitchen': 'Kitchen',
    'plumbing': 'Plumbing',
    'project_specs': 'Project Specifications',
    'market_benchmarks': 'Market Cost Benchmarks',
    'engineering_quantities': 'Engineering Quantities',
    'total_labor': 'Total Labor',
    'total_material': 'Total Material',
    'grand_total': 'Estimated Grand Total',
    'download_pdf': 'Download Estimate (PDF)',
    'calc_note': '* Note: Estimates include material wastage factors (approx 10-15%). Final site measurements prevail.',
    'length_ft': 'Length (FT)',
    'height_ft': 'Height (FT)',
    'width_ft': 'Width (FT)',
    'wall_thickness': 'Wall Thickness',
    'mix_ratio': 'Mix Ratio',
    'plaster_type': 'Plaster Type',
    'thickness_mm': 'Thickness (MM)',
    'material_type': 'Material Type',
    'light_fan_points': 'Light / Fan Points (NOS)',
    'amp6_points': '6 Amp Points (NOS)',
    'amp15_points': '15 Amp Points (NOS)',
    'ac_points': 'A.C. Points (NOS)',
    'geyser_points': 'Geyser Points (NOS)',
    'exhaust_points': 'Exhaust Points (NOS)',
    'tv_points': 'TV Points (NOS)',
    'internet_points': 'Internet Points (NOS)',
    'tile_size': 'Tile Size (Market Standard)',
    'stone_type': 'Stone / Granite Type',
    'no_frames': 'No. of Frames',
    'size_rft': 'Size (Running Foot)',
    'knobs_per_frame': 'Knobs per Frame',
    'kitchen_type': 'Kitchen Type',
    'countertop_material': 'Countertop Material',
    'main_length_ft': 'Main Length (FT)',
    'dedo_area_sqft': 'Dedo Area (SQFT)',
    'bathrooms_nos': 'Bathrooms (NOS)',
    'kitchens_nos': 'Kitchens (NOS)',
    'extra_points': 'Extra Points',
    'labor_rate_sqft': 'Labor Rate (₹ / SQFT)',
    'material_rate_sqft': 'Material Rate (₹ / SQFT)'
  },
  hi: {
    'dashboard': 'डैशबोर्ड',
    'clients': 'ग्राहक',
    'estimates': 'अनुमान',
    'items': 'आइटम',
    'reminders': 'अनुस्मारक',
    'insights': 'व्यावसायिक अंतर्दृष्टि',
    'sketch': 'स्केच पैड',
    'converter': 'इकाई रूपांतरण',
    'calculator': 'कैलकुलेटर',
    'construction-calc': 'इंजीनियरिंग टूलसेट',
    'admin': 'कंपनी की पहचान',
    'profile': 'मेरी प्रोफाइल',
    'logout': 'लॉगआउट',
    'super-admin': 'सुपर एडमिन',
    'menu': 'मेनू',
    'total_estimates': 'कुल अनुमान',
    'active_clients': 'सक्रिय ग्राहक',
    'pending_tasks': 'लंबित कार्य',
    'total_revenue': 'कुल राजस्व',
    'recent_estimates': 'हाल के अनुमान',
    'view_all': 'सभी देखें',
    'create_new': 'नया बनाएं',
    'search': 'खोजें...',
    'settings': 'सेटिंग्स',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'delete': 'हटाएं',
    'edit': 'संपादित करें',
    'add': 'जोड़ें',
    'name': 'नाम',
    'email': 'ईमेल',
    'phone': 'फ़ोन',
    'address': 'पता',
    'status': 'स्थिति',
    'date': 'तारीख',
    'amount': 'राशि',
    'action': 'कार्रवाई',
    'language': 'भाषा',
    'english': 'अंग्रेज़ी',
    'hindi': 'हिंदी',
    'gujarati': 'गुजराती',
    'category': 'श्रेणी',
    'from': 'से',
    'to': 'तक',
    'enter_value': 'मान दर्ज करें',
    'converted_result': 'परिवर्तित परिणाम',
    'copy': 'परिणाम कॉपी करें',
    'copied': 'कॉपी किया गया!',
    'common_conversions': 'सामान्य रूपांतरण',
    'land_units': 'भूमि इकाइयाँ (भारत)',
    'did_you_know': 'क्या आप जानते हैं?',
    'brass_info': 'भारतीय निर्माण में, "ब्रास" आयतन के लिए एक सामान्य इकाई है, जो १०० घन फीट के बराबर है। हमारे कनवर्टर में स्थानीय परियोजना सटीकता के लिए सूत और बीघा जैसी विशेष इकाइयाँ शामिल हैं।',
    'converter_desc': 'विभिन्न निर्माण और इंजीनियरिंग इकाइयों के बीच रूपांतरण करें।',
    'Length': 'लंबाई',
    'Area': 'क्षेत्रफल',
    'Volume': 'आयतन',
    'Land (India)': 'भूमि (भारत)',
    'brick_work': 'ईंट का काम',
    'plastering': 'प्लास्टर',
    'wall_paint': 'दीवार पेंट',
    'gypsum': 'जिप्सम',
    'electrical': 'इलेक्ट्रिकल',
    'flooring': 'फ्लोरिंग',
    'stone_work': 'पत्थर का काम',
    'doors': 'दरवाजे',
    'windows': 'खिड़कियां',
    'frame_work': 'फ्रेम वर्क',
    'kitchen': 'रसोई',
    'plumbing': 'प्लंबिंग',
    'project_specs': 'परियोजना विनिर्देश',
    'market_benchmarks': 'बाजार लागत बेंचमार्क',
    'engineering_quantities': 'इंजीनियरिंग मात्रा',
    'total_labor': 'कुल श्रम',
    'total_material': 'कुल सामग्री',
    'grand_total': 'अनुमानित कुल योग',
    'download_pdf': 'अनुमान डाउनलोड करें (PDF)',
    'calc_note': '* नोट: अनुमानों में सामग्री बर्बादी कारक (लगभग १०-१५%) शामिल हैं। अंतिम साइट माप मान्य होंगे।',
    'length_ft': 'लंबाई (FT)',
    'height_ft': 'ऊंचाई (FT)',
    'width_ft': 'चौड़ाई (FT)',
    'wall_thickness': 'दीवार की मोटाई',
    'mix_ratio': 'मिश्रण अनुपात',
    'plaster_type': 'प्लास्टर का प्रकार',
    'thickness_mm': 'मोटाई (MM)',
    'material_type': 'सामग्री का प्रकार',
    'light_fan_points': 'लाइट / फैन पॉइंट (NOS)',
    'amp6_points': '६ एम्प पॉइंट (NOS)',
    'amp15_points': '१५ एम्प पॉइंट (NOS)',
    'ac_points': 'ए.सी. पॉइंट (NOS)',
    'geyser_points': 'गीजर पॉइंट (NOS)',
    'exhaust_points': 'एग्जॉस्ट पॉइंट (NOS)',
    'tv_points': 'टी.वी. पॉइंट (NOS)',
    'internet_points': 'इंटरनेट पॉइंट (NOS)',
    'tile_size': 'टाइल का आकार',
    'stone_type': 'पत्थर / ग्रेनाइट का प्रकार',
    'no_frames': 'फ्रेम की संख्या',
    'size_rft': 'आकार (रनिंग फुट)',
    'knobs_per_frame': 'प्रति फ्रेम नॉब्स',
    'kitchen_type': 'रसोई का प्रकार',
    'countertop_material': 'काउंटरटॉप सामग्री',
    'main_length_ft': 'मुख्य लंबाई (FT)',
    'dedo_area_sqft': 'डेडों क्षेत्रफल (SQFT)',
    'bathrooms_nos': 'बाथरूम (NOS)',
    'kitchens_nos': 'रसोई (NOS)',
    'extra_points': 'अतिरिक्त पॉइंट',
    'labor_rate_sqft': 'श्रम दर (₹ / SQFT)',
    'material_rate_sqft': 'सामग्री दर (₹ / SQFT)'
  },
  gu: {
    'dashboard': 'ડેશબોર્ડ',
    'clients': 'ગ્રાહકો',
    'estimates': 'અંદાજો',
    'items': 'આઇટમ્સ',
    'reminders': 'રિમાઇન્ડર્સ',
    'insights': 'વ્યવસાયિક આંતરદૃષ્ટિ',
    'sketch': 'સ્કેચ પેડ',
    'converter': 'એકમ રૂપાંતરણ',
    'calculator': 'કેલ્ક્યુલેટર',
    'construction-calc': 'એન્જિનિયરિંગ ટૂલસેટ',
    'admin': 'કંપનીની ઓળખ',
    'profile': 'મારી પ્રોફાઇલ',
    'logout': 'લોગઆઉટ',
    'super-admin': 'સુપર એડમિન',
    'menu': 'મેનુ',
    'total_estimates': 'કુલ અંદાજો',
    'active_clients': 'સક્રિય ગ્રાહકો',
    'pending_tasks': 'બાકી કાર્યો',
    'total_revenue': 'કુલ આવક',
    'recent_estimates': 'તાજેતરના અંદાજો',
    'view_all': 'બધું જુઓ',
    'create_new': 'નવું બનાવો',
    'search': 'શોધો...',
    'settings': 'સેટિંગ્સ',
    'save': 'સાચવો',
    'cancel': 'રદ કરો',
    'delete': 'કાઢી નાખો',
    'edit': 'ફેરફાર કરો',
    'add': 'ઉમેરો',
    'name': 'નામ',
    'email': 'ઇમેઇલ',
    'phone': 'ફોન',
    'address': 'સરનામું',
    'status': 'સ્થિતિ',
    'date': 'તારીખ',
    'amount': 'રકમ',
    'action': 'ક્રિયા',
    'language': 'ભાષા',
    'english': 'અંગ્રેજી',
    'hindi': 'હિન્દી',
    'gujarati': 'ગુજરાતી',
    'category': 'શ્રેણી',
    'from': 'થી',
    'to': 'સુધી',
    'enter_value': 'કિંમત દાખલ કરો',
    'converted_result': 'રૂપાંતરિત પરિણામ',
    'copy': 'પરિણામ કોપી કરો',
    'copied': 'કોપી થઈ ગયું!',
    'common_conversions': 'સામાન્ય રૂપાંતરણો',
    'land_units': 'જમીન એકમો (ભારત)',
    'did_you_know': 'શું તમે જાણો છો?',
    'brass_info': 'ભારતીય બાંધકામમાં, "બ્રાસ" એ કદ માટેનો સામાન્ય એકમ છે, જે ૧૦૦ ઘન ફૂટ બરાબર છે. અમારા કન્વર્ટરમાં સ્થાનિક પ્રોજેક્ટ ચોકસાઈ માટે સૂત અને વીઘા જેવા વિશિષ્ટ એકમો શામેલ છે.',
    'converter_desc': 'વિવિધ બાંધકામ અને એન્જિનિયરિંગ એકમો વચ્ચે રૂપાંતર કરો.',
    'Length': 'લંબાઈ',
    'Area': 'ક્ષેત્રફળ',
    'Volume': 'કદ',
    'Land (India)': 'જમીન (ભારત)',
    'brick_work': 'ઈંટનું કામ',
    'plastering': 'પ્લાસ્ટર',
    'wall_paint': 'દીવાલ પેઇન્ટ',
    'gypsum': 'જીપ્સમ',
    'electrical': 'ઇલેક્ટ્રિકલ',
    'flooring': 'ફ્લોરિંગ',
    'stone_work': 'પથ્થરનું કામ',
    'doors': 'દરવાજા',
    'windows': 'બારીઓ',
    'frame_work': 'ફ્રેમ વર્ક',
    'kitchen': 'રસોડું',
    'plumbing': 'પ્લમ્બિંગ',
    'project_specs': 'પ્રોજેક્ટ વિશિષ્ટતાઓ',
    'market_benchmarks': 'બજાર ખર્ચ બેન્ચમાર્ક',
    'engineering_quantities': 'એન્જિનિયરિંગ જથ્થો',
    'total_labor': 'કુલ શ્રમ',
    'total_material': 'કુલ સામગ્રી',
    'grand_total': 'અંદાજિત કુલ સરવાળો',
    'download_pdf': 'અંદાજ ડાઉનલોડ કરો (PDF)',
    'calc_note': '* નોંધ: અંદાજોમાં સામગ્રીના બગાડના પરિબળો (આશરે ૧૦-૧૫%) શામેલ છે. અંતિમ સાઇટ માપ પ્રચલિત રહેશે.',
    'length_ft': 'લંબાઈ (FT)',
    'height_ft': 'ઊંચાઈ (FT)',
    'width_ft': 'પહોળાઈ (FT)',
    'wall_thickness': 'દીવાલની જાડાઈ',
    'mix_ratio': 'મિશ્રણ ગુણોત્તર',
    'plaster_type': 'પ્લાસ્ટરનો પ્રકાર',
    'thickness_mm': 'જાડાઈ (MM)',
    'material_type': 'સામગ્રીનો પ્રકાર',
    'light_fan_points': 'લાઇટ / ફેન પોઈન્ટ (NOS)',
    'amp6_points': '૬ એમ્પ પોઈન્ટ (NOS)',
    'amp15_points': '૧૫ એમ્પ પોઈન્ટ (NOS)',
    'ac_points': 'એ.સી. પોઈન્ટ (NOS)',
    'geyser_points': 'ગીઝર પોઈન્ટ (NOS)',
    'exhaust_points': 'એક્ઝોસ્ટ પોઈન્ટ (NOS)',
    'tv_points': 'ટી.વી. પોઈન્ટ (NOS)',
    'internet_points': 'ઇન્ટરનેટ પોઈન્ટ (NOS)',
    'tile_size': 'ટાઇલનું માપ',
    'stone_type': 'પથ્થર / ગ્રેનાઈટનો પ્રકાર',
    'no_frames': 'ફ્રેમની સંખ્યા',
    'size_rft': 'માપ (રનિંગ ફૂટ)',
    'knobs_per_frame': 'ફ્રેમ દીઠ નોબ્સ',
    'kitchen_type': 'રસોડાનો પ્રકાર',
    'countertop_material': 'કાઉન્ટરટોપ સામગ્રી',
    'main_length_ft': 'મુખ્ય લંબાઈ (FT)',
    'dedo_area_sqft': 'ડેડો ક્ષેત્રફળ (SQFT)',
    'bathrooms_nos': 'બાથરૂમ (NOS)',
    'kitchens_nos': 'રસોડું (NOS)',
    'extra_points': 'વધારાના પોઈન્ટ',
    'labor_rate_sqft': 'શ્રમ દર (₹ / SQFT)',
    'material_rate_sqft': 'સામગ્રી દર (₹ / SQFT)'
 
  }
};

const hindiDigits = ['०', '१', '२', '३', '४', '५', '६', '७', '८', '९'];
const gujaratiDigits = ['૦', '૧', '૨', '૩', '૪', '૫', '૬', '૭', '૮', '૯'];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const formatNumber = (num: number | string): string => {
    const str = num.toString();
    if (language === 'en') return str;

    const digits = language === 'hi' ? hindiDigits : gujaratiDigits;
    return str.replace(/\d/g, (d) => digits[parseInt(d)]);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatNumber }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
