import { 
  FileText, 
  Package, 
  Bell, 
  Users, 
  TrendingUp, 
  PenTool, 
  Ruler, 
  Calculator as CalcIcon, 
  HardHat, 
  Receipt, 
  Briefcase,
  Zap,
  Smartphone,
  ShieldAlert,
  ShieldCheck,
  User,
  LogOut,
  Menu,
  X,
  Construction,
  Lock,
  ChevronLeft,
  ChevronRight,
  Database,
  Mail,
  PlusCircle,
  AlertTriangle,
  Clock,
  CheckCircle2,
  Phone,
  MapPin,
  Edit2,
  Plus,
  Trash2,
  Building2,
  Globe,
  MessageSquare,
  Save,
  Image as ImageIcon,
  Layout as LayoutIcon,
  FileText as FileIcon,
  Package as PackageIcon,
  Check,
  CreditCard,
  Upload
} from 'lucide-react';

export const ALL_FEATURES = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutIcon },
  { id: 'clients', label: 'Clients', icon: Users },
  { id: 'estimates', label: 'Estimates', icon: FileText },
  { id: 'invoices', label: 'Invoices', icon: Receipt },
  { id: 'projects', label: 'Projects', icon: Briefcase },
  { id: 'items', label: 'Items', icon: Package },
  { id: 'reminders', label: 'Reminders', icon: Bell },
  { id: 'insights', label: 'Business Insights', icon: TrendingUp },
  { id: 'sketch', label: 'Sketch Pad', icon: PenTool },
  { id: 'converter', label: 'Unit Conversion', icon: Ruler },
  { id: 'calculator', label: 'Scientific Calculator', icon: CalcIcon },
  { id: 'construction-calc', label: 'Engineering Toolset', icon: HardHat },
  { id: 'calc-brick', label: 'Brick Work Calc', icon: HardHat },
  { id: 'calc-plaster', label: 'Plastering Calc', icon: HardHat },
  { id: 'calc-paint', label: 'Wall Paint Calc', icon: HardHat },
  { id: 'calc-gypsum', label: 'Gypsum Calc', icon: HardHat },
  { id: 'calc-electrical', label: 'Electrical Calc', icon: Zap },
  { id: 'calc-flooring', label: 'Flooring/Tile Calc', icon: HardHat },
  { id: 'calc-stone', label: 'Stone Work Calc', icon: HardHat },
  { id: 'calc-doors', label: 'Doors Calc', icon: HardHat },
  { id: 'calc-windows', label: 'Windows Calc', icon: HardHat },
  { id: 'calc-frame', label: 'Frame Work Calc', icon: HardHat },
  { id: 'calc-kitchen', label: 'Kitchen Calc', icon: HardHat },
  { id: 'calc-plumbing', label: 'Plumbing Calc', icon: HardHat },
  { id: 'civil-drawing', label: 'Civil Drawing', icon: PenTool },
];

export const FEATURE_IDS = ALL_FEATURES.map(f => f.id);
